export type LivingExpenseCategory =
  | 'FOOD'
  | 'TRANSPORT'
  | 'ENTERTAINMENT'
  | 'HEALTH'
  | 'LIFESTYLE'
  | 'UNEXPECTED';

export interface LivingExpenseItem {
  id: string;
  category: LivingExpenseCategory;
  title: string;
  description: string;
  minAmount: number;
  maxAmount: number;
}

/** Вес категории при случайном выборе чека за ход (чем выше — тем чаще). */
export const LIVING_EXPENSE_CATEGORY_WEIGHTS: Record<LivingExpenseCategory, number> = {
  FOOD: 40,
  TRANSPORT: 30,
  ENTERTAINMENT: 12,
  HEALTH: 6,
  LIFESTYLE: 7,
  UNEXPECTED: 5,
};

export const LIVING_EXPENSES: LivingExpenseItem[] = [
  // ── FOOD (18) ──────────────────────────────────────────────────────────────
  {
    id: 'morning_coffee',
    category: 'FOOD',
    title: 'Утренний кофе',
    description: 'Капучино с собой. Без него день не начинается, а кошелёк уже вздохнул.',
    minAmount: 10,
    maxAmount: 18,
  },
  {
    id: 'business_lunch',
    category: 'FOOD',
    title: 'Бизнес-ланч',
    description: 'Комплексный обед в кафе у офиса. Суп, салат и надежда, что это «деловая встреча».',
    minAmount: 12,
    maxAmount: 28,
  },
  {
    id: 'street_food',
    category: 'FOOD',
    title: 'Уличная еда',
    description: 'Шаурма на бегу. Вкусно, быстро, следы на галстуке — бесплатно.',
    minAmount: 10,
    maxAmount: 16,
  },
  {
    id: 'grocery_snacks',
    category: 'FOOD',
    title: 'Перекус из магазина',
    description: 'Йогурт, батончик и внутренний голос, который говорил «не бери чипсы».',
    minAmount: 10,
    maxAmount: 22,
  },
  {
    id: 'delivery_pizza',
    category: 'FOOD',
    title: 'Пицца на дом',
    description: 'Заказ после тяжёлого дня. Курьер приехал быстрее, чем вы успели пожалеть.',
    minAmount: 18,
    maxAmount: 35,
  },
  {
    id: 'sushi_box',
    category: 'FOOD',
    title: 'Суши-сет',
    description: 'Роллы «на двоих», съеденные в одиночку за просмотр графиков.',
    minAmount: 22,
    maxAmount: 45,
  },
  {
    id: 'bakery_croissant',
    category: 'FOOD',
    title: 'Круассан в пекарне',
    description: 'Слоёная булка, которая крошится точнее, чем ваш портфель в понедельник.',
    minAmount: 10,
    maxAmount: 14,
  },
  {
    id: 'energy_drink',
    category: 'FOOD',
    title: 'Энергетик',
    description: 'Банка мотивации. Действует 40 минут, потом — снова реальность.',
    minAmount: 10,
    maxAmount: 15,
  },
  {
    id: 'office_vending',
    category: 'FOOD',
    title: 'Автомат в офисе',
    description: 'Сэндвич, который выглядит так, будто его листали вчера.',
    minAmount: 10,
    maxAmount: 18,
  },
  {
    id: 'late_night_doner',
    category: 'FOOD',
    title: 'Ночной донер',
    description: 'Закрытие торговой сессии и открытие холодильника не помогли — пришлось идти на улицу.',
    minAmount: 12,
    maxAmount: 20,
  },
  {
    id: 'farmers_market',
    category: 'FOOD',
    title: 'Рынок: овощи',
    description: 'Свежая зелень. Потом три дня в холодильнике — свежая ностальгия.',
    minAmount: 15,
    maxAmount: 30,
  },
  {
    id: 'bubble_tea',
    category: 'FOOD',
    title: 'Бабл-ти',
    description: 'Чай с шариками. Вы не поняли тренд, но заказали снова.',
    minAmount: 10,
    maxAmount: 16,
  },
  {
    id: 'steakhouse_mini',
    category: 'FOOD',
    title: 'Стейк «по случаю»',
    description: 'Повод: хороший день на бирже. Плохой день — тоже повод.',
    minAmount: 35,
    maxAmount: 65,
  },
  {
    id: 'meal_prep',
    category: 'FOOD',
    title: 'Готовая еда',
    description: 'Контейнеры на неделю. Съедите два, остальное — артефакты археологии.',
    minAmount: 25,
    maxAmount: 48,
  },
  {
    id: 'birthday_cake_slice',
    category: 'FOOD',
    title: 'Кусок торта',
    description: 'Коллега празднует. Вы улыбаетесь и считаете калории в долларах.',
    minAmount: 10,
    maxAmount: 18,
  },
  {
    id: 'wine_cheese',
    category: 'FOOD',
    title: 'Вино и сыр',
    description: 'Пятничный вечер. Рынок закрыт, настроение — нет.',
    minAmount: 28,
    maxAmount: 55,
  },

  // ── TRANSPORT (12) ─────────────────────────────────────────────────────────
  {
    id: 'metro_commute',
    category: 'TRANSPORT',
    title: 'Проезд на метро',
    description: 'Туда-обратно. В вагоне кто-то уже обсуждает ваши любимые акции.',
    minAmount: 10,
    maxAmount: 16,
  },
  {
    id: 'taxi_rush',
    category: 'TRANSPORT',
    title: 'Такси',
    description: 'Опаздываете на встречу. Водитель знает короткий путь и длинный счёт.',
    minAmount: 18,
    maxAmount: 42,
  },
  {
    id: 'rideshare_surge',
    category: 'TRANSPORT',
    title: 'Каршеринг в час пик',
    description: 'Множитель ×2.5. Как волатильность, только обиднее.',
    minAmount: 22,
    maxAmount: 50,
  },
  {
    id: 'bus_ticket',
    category: 'TRANSPORT',
    title: 'Автобус',
    description: 'Дешевле такси, дольше жизни. Зато время на новости почитать.',
    minAmount: 10,
    maxAmount: 14,
  },
  {
    id: 'gas_refill',
    category: 'TRANSPORT',
    title: 'Бензин',
    description: 'Полбака. Цена за литр растёт быстрее, чем ваш дивидендный портфель.',
    minAmount: 35,
    maxAmount: 75,
  },
  {
    id: 'parking_hour',
    category: 'TRANSPORT',
    title: 'Парковка в центре',
    description: 'Час у бизнес-центра. Дороже, чем казалось в момент «припаркуюсь ненадолго».',
    minAmount: 12,
    maxAmount: 28,
  },
  {
    id: 'scooter_rent',
    category: 'TRANSPORT',
    title: 'Аренда самоката',
    description: '15 минут ветра в лицо и одна яма, которую вы запомните надолго.',
    minAmount: 10,
    maxAmount: 20,
  },
  {
    id: 'train_suburb',
    category: 'TRANSPORT',
    title: 'Электричка',
    description: 'Выезд за город. Место у окна занято, вид — на чужой ноутбук.',
    minAmount: 10,
    maxAmount: 18,
  },
  {
    id: 'car_wash_basic',
    category: 'TRANSPORT',
    title: 'Мойка авто',
    description: 'Машина сияет. Прогноз дождя — через час, бесплатно.',
    minAmount: 15,
    maxAmount: 35,
  },
  {
    id: 'toll_road',
    category: 'TRANSPORT',
    title: 'Платная дорога',
    description: 'Сэкономили 8 минут и потратили на это больше, чем планировали.',
    minAmount: 10,
    maxAmount: 25,
  },
  {
    id: 'airport_transfer',
    category: 'TRANSPORT',
    title: 'Трансфер',
    description: 'Поездка в аэропорт. Вы ещё не в отпуске, а деньги уже летят.',
    minAmount: 45,
    maxAmount: 95,
  },

  // ── ENTERTAINMENT (7) ──────────────────────────────────────────────────────
  {
    id: 'cinema_ticket',
    category: 'ENTERTAINMENT',
    title: 'Билет в кино',
    description: 'Премьера блокбастера. Попкорн не входит — он никогда не входит.',
    minAmount: 12,
    maxAmount: 22,
  },
  {
    id: 'streaming_sub',
    category: 'ENTERTAINMENT',
    title: 'Подписка на стриминг',
    description: 'Ещё один сериал, который вы не досмотрите из-за свечей на графике.',
    minAmount: 10,
    maxAmount: 18,
  },
  {
    id: 'bar_draft',
    category: 'ENTERTAINMENT',
    title: 'Пиво в баре',
    description: 'Один бокал после удачной сделки. Два — после неудачной.',
    minAmount: 10,
    maxAmount: 24,
  },
  {
    id: 'mobile_game',
    category: 'ENTERTAINMENT',
    title: 'Внутриигровая покупка',
    description: '«Только один раз». Третий раз за неделю.',
    minAmount: 10,
    maxAmount: 30,
  },
  {
    id: 'bowling_night',
    category: 'ENTERTAINMENT',
    title: 'Боулинг с друзьями',
    description: 'Страйк! Счёт в баре после — тоже впечатляющий.',
    minAmount: 25,
    maxAmount: 55,
  },
  {
    id: 'concert_ticket',
    category: 'ENTERTAINMENT',
    title: 'Билет на концерт',
    description: 'Живая музыка. Сосед пел громче артиста — бесплатно.',
    minAmount: 40,
    maxAmount: 120,
  },

  // ── HEALTH (5) ─────────────────────────────────────────────────────────────
  {
    id: 'cold_medicine',
    category: 'HEALTH',
    title: 'Лекарства от простуды',
    description: 'Простуда не знает про ваш дедлайн по отчёту.',
    minAmount: 12,
    maxAmount: 28,
  },
  {
    id: 'pharmacy_vitamins',
    category: 'HEALTH',
    title: 'Витамины',
    description: 'Комплекс «для энергии». Работает на уровне плацебо и надежды.',
    minAmount: 18,
    maxAmount: 45,
  },
  {
    id: 'doctor_visit',
    category: 'HEALTH',
    title: 'Визит к врачу',
    description: 'Осмотр и совет «меньше нервничать». Спасибо, доктор.',
    minAmount: 35,
    maxAmount: 85,
  },
  {
    id: 'dentist_checkup',
    category: 'HEALTH',
    title: 'Стоматолог',
    description: 'Плановый осмотр. Улыбка стала дороже, зато искреннее.',
    minAmount: 45,
    maxAmount: 120,
  },
  {
    id: 'eye_drops',
    category: 'HEALTH',
    title: 'Капли для глаз',
    description: 'После восьми часов перед монитором. Глаза благодарят, кошелёк — нет.',
    minAmount: 10,
    maxAmount: 22,
  },

  // ── LIFESTYLE (6) ──────────────────────────────────────────────────────────
  {
    id: 'barbershop',
    category: 'LIFESTYLE',
    title: 'Стрижка',
    description: 'Барбершоп. Вас снова узнают на совещании.',
    minAmount: 20,
    maxAmount: 45,
  },
  {
    id: 'dry_cleaning',
    category: 'LIFESTYLE',
    title: 'Химчистка',
    description: 'Рубашка выжила после бизнес-ланча. Почти героически.',
    minAmount: 12,
    maxAmount: 30,
  },
  {
    id: 'phone_case',
    category: 'LIFESTYLE',
    title: 'Чехол для телефона',
    description: 'Старый треснул. Новый тоже треснет, но позже.',
    minAmount: 10,
    maxAmount: 35,
  },
  {
    id: 'laundry_service',
    category: 'LIFESTYLE',
    title: 'Прачечная',
    description: 'Стопка вещей превратилась в аккуратный стек. Магия за деньги.',
    minAmount: 15,
    maxAmount: 40,
  },
  {
    id: 'house_plant',
    category: 'LIFESTYLE',
    title: 'Комнатное растение',
    description: 'Фикус для «уюта». Выживет дольше одной сделки — надеемся.',
    minAmount: 18,
    maxAmount: 42,
  },
  {
    id: 'tailor_hem',
    category: 'LIFESTYLE',
    title: 'Подшив брюк',
    description: 'Наконец-то идеальная длина. Три года откладывали.',
    minAmount: 12,
    maxAmount: 28,
  },

  // ── UNEXPECTED (6) ─────────────────────────────────────────────────────────
  {
    id: 'parking_fine',
    category: 'UNEXPECTED',
    title: 'Штраф за парковку',
    description: 'Место было «всего на пять минут». Штраф — на долгую память.',
    minAmount: 40,
    maxAmount: 120,
  },
  {
    id: 'phone_screen_crack',
    category: 'UNEXPECTED',
    title: 'Замена стекла',
    description: 'Уронили телефон. Гравитация не принимает апелляции.',
    minAmount: 55,
    maxAmount: 150,
  },
  {
    id: 'colleague_gift',
    category: 'UNEXPECTED',
    title: 'Подарок коллеге',
    description: 'Сбор в офисе. Вы не помните имя, но помните про вежливость.',
    minAmount: 25,
    maxAmount: 60,
  },
  {
    id: 'home_repair_minor',
    category: 'UNEXPECTED',
    title: 'Мелкий ремонт дома',
    description: 'Кран капал. Теперь капает деньгами из вашего счёта.',
    minAmount: 45,
    maxAmount: 180,
  },
  {
    id: 'lost_key_copy',
    category: 'UNEXPECTED',
    title: 'Вскрытие замка',
    description: 'Ключи остались внутри. Вечер стал приключением.',
    minAmount: 60,
    maxAmount: 200,
  },
  {
    id: 'tax_late_fee',
    category: 'UNEXPECTED',
    title: 'Пеня по счёту',
    description: 'Забыли оплатить квитанцию. Напоминание пришло с процентами.',
    minAmount: 35,
    maxAmount: 95,
  },
];
