import { MarketSector } from '@prisma/client';

export type StaticNewsKind = 'MARKET' | 'INSIDER' | 'RUMOR';

export interface StaticNewsTemplate {
  id: string;
  kind: StaticNewsKind;
  sector: MarketSector;
  title: string;
  body: string;
  sentimentScore: number;
  expectedMovePercent?: number;
  turnsUntilImpact?: number;
  insiderInfo?: string;
}

export const NEWS_TEMPLATES: StaticNewsTemplate[] = [
  // ── TECHNOLOGY ─────────────────────────────────────────────────────────────
  {
    id: 'tech_market_01',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: '{company}: выручка обогнала прогнозы',
    body: 'Квартальный отчёт {company} ({ticker}) превзошёл ожидания аналитиков. Рынок отреагировал ростом котировок на фоне сильного спроса на облачные сервисы и подписочные продукты.',
    sentimentScore: 0.52,
  },
  {
    id: 'tech_market_02',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: 'Сектор технологий: волна сокращений',
    body: '{company} ({ticker}) объявила о программе оптимизации штата. Инвесторы опасаются замедления инвестиций в R&D, хотя руководство обещает сохранить ключевые продуктовые направления.',
    sentimentScore: -0.48,
  },
  {
    id: 'tech_market_03',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: 'Регуляторы внимательнее смотрят на {ticker}',
    body: 'Антимонопольное ведомство запросило дополнительные разъяснения у {company}. Акции просели внутри дня, но аналитики считают риск штрафов умеренным.',
    sentimentScore: -0.35,
  },
  {
    id: 'tech_market_04',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: '{company} запускает новую линейку устройств',
    body: 'Презентация продуктов {company} ({ticker}) собрала рекордный онлайн-аудиторий. Предзаказы превысили прошлогодние показатели, что поддержало оптимизм по сектору.',
    sentimentScore: 0.44,
  },
  {
    id: 'tech_market_05',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: 'ИИ-гонка: {ticker} усиливает партнёрства',
    body: '{company} заключила стратегическое соглашение с крупным поставщиком вычислительных мощностей. Рынок оценивает сделку как шаг к укреплению позиций в сегменте генеративного ИИ.',
    sentimentScore: 0.38,
  },
  {
    id: 'tech_market_06',
    kind: 'MARKET',
    sector: MarketSector.TECHNOLOGY,
    title: 'Технологии без явного лидера',
    body: 'Индекс сектора двигался в узком диапазоне. {company} ({ticker}) опубликовала операционные метрики в рамках ожиданий — существенных сюрпризов для рынка не было.',
    sentimentScore: 0.05,
  },
  {
    id: 'tech_insider_01',
    kind: 'INSIDER',
    sector: MarketSector.TECHNOLOGY,
    title: 'Инсайд: {ticker} готовит крупное обновление',
    body: 'По данным источника, {company} планирует анонс, который может заметно повлиять на выручку следующего квартала.',
    sentimentScore: 0.55,
    expectedMovePercent: 11,
    turnsUntilImpact: 3,
    insiderInfo: 'Источник близок к продуктовому подразделению, детали пока не публичны.',
  },
  {
    id: 'tech_insider_02',
    kind: 'INSIDER',
    sector: MarketSector.TECHNOLOGY,
    title: 'Инсайд: задержка релиза ударит по {ticker}',
    body: 'Внутренние обсуждения указывают на перенос ключевого релиза {company} минимум на один квартал.',
    sentimentScore: -0.5,
    expectedMovePercent: -9,
    turnsUntilImpact: 2,
    insiderInfo: 'Информация получена от контрагента по цепочке поставок.',
  },
  {
    id: 'tech_rumor_01',
    kind: 'RUMOR',
    sector: MarketSector.TECHNOLOGY,
    title: 'Слух: {ticker} ведёт переговоры о поглощении',
    body: 'На рынке обсуждают возможную сделку M&A с участием {company}. Официальных комментариев нет, надёжность информации низкая.',
    sentimentScore: 0.12,
  },
  {
    id: 'tech_rumor_02',
    kind: 'RUMOR',
    sector: MarketSector.TECHNOLOGY,
    title: 'Слух: утечка данных в {company}',
    body: 'Анонимный канал утверждает, что у {company} ({ticker}) произошёл инцидент информационной безопасности. Компания отказалась от комментариев.',
    sentimentScore: -0.18,
  },

  // ── HEALTHCARE ────────────────────────────────────────────────────────────
  {
    id: 'health_market_01',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: '{company}: одобрение препарата поддержало акции',
    body: 'Регулятор выдал разрешение на применение нового лекарства {company} ({ticker}). Аналитики пересмотрели прогнозы продаж в сторону повышения.',
    sentimentScore: 0.58,
  },
  {
    id: 'health_market_02',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: 'Клинические испытания {ticker} приостановлены',
    body: '{company} сообщила о временной остановке исследования из-за протокольных вопросов. Рынок воспринял новость настороженно, хотя компания называет паузу стандартной процедурой.',
    sentimentScore: -0.55,
  },
  {
    id: 'health_market_03',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: 'Спрос на диагностику растёт',
    body: 'Отчёт {company} ({ticker}) показал устойчивый рост заказов на диагностическое оборудование. Сектор здравоохранения выглядит стабильнее широкого рынка.',
    sentimentScore: 0.4,
  },
  {
    id: 'health_market_04',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: 'Давление на маржу фармсектора',
    body: 'Государство обсуждает меры по снижению цен на ряд препаратов. {company} ({ticker}) подешевела вместе с отраслью, инвесторы ждут деталей регулирования.',
    sentimentScore: -0.42,
  },
  {
    id: 'health_market_05',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: '{company} расширяет сеть клиник',
    body: 'Стратегия {company} ({ticker}) по вертикальной интеграции получила одобрение совета директоров. Рынок оценивает шаг как долгосрочный, но капиталоёмкий.',
    sentimentScore: 0.22,
  },
  {
    id: 'health_market_06',
    kind: 'MARKET',
    sector: MarketSector.HEALTHCARE,
    title: 'Здравоохранение: спокойная сессия',
    body: 'Котировки {company} ({ticker}) изменились незначительно. Участники рынка ждут отраслевой конференции на следующей неделе.',
    sentimentScore: 0,
  },
  {
    id: 'health_insider_01',
    kind: 'INSIDER',
    sector: MarketSector.HEALTHCARE,
    title: 'Инсайд: позитивные данные по {ticker}',
    body: 'Источник утверждает, что промежуточные результаты исследования {company} лучше консенсус-прогноза.',
    sentimentScore: 0.6,
    expectedMovePercent: 14,
    turnsUntilImpact: 4,
    insiderInfo: 'Данные ещё не опубликованы в открытом доступе.',
  },
  {
    id: 'health_insider_02',
    kind: 'INSIDER',
    sector: MarketSector.HEALTHCARE,
    title: 'Инсайд: регулятор может затянуть решение по {ticker}',
    body: 'По внутренним каналам обсуждают дополнительные запросы к досье {company}, что сдвинет сроки одобрения.',
    sentimentScore: -0.45,
    expectedMovePercent: -10,
    turnsUntilImpact: 3,
    insiderInfo: 'Информация получена от консультанта по регуляторным вопросам.',
  },
  {
    id: 'health_rumor_01',
    kind: 'RUMOR',
    sector: MarketSector.HEALTHCARE,
    title: 'Слух: {company} ищет партнёра по производству',
    body: 'Рынок обсуждает возможный контракт на аутсорсинг производства для {ticker}. Подтверждений нет.',
    sentimentScore: 0.08,
  },
  {
    id: 'health_rumor_02',
    kind: 'RUMOR',
    sector: MarketSector.HEALTHCARE,
    title: 'Слух: судебный иск против {ticker}',
    body: 'В профессиональных чатах появилась информация о потенциальном иске к {company}. Юристы называют риск преждевременным.',
    sentimentScore: -0.15,
  },

  // ── FINANCE ────────────────────────────────────────────────────────────────
  {
    id: 'fin_market_01',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: '{company}: сильный квартал по комиссиям',
    body: 'Доходы {company} ({ticker}) от транзакционного бизнеса выросли быстрее рынка. Инвесторы отмечают устойчивый поток розничных клиентов.',
    sentimentScore: 0.46,
  },
  {
    id: 'fin_market_02',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: 'Резервы под кредиты бьют по {ticker}',
    body: '{company} увеличила резервы на возможные потери по кредитному портфелю. Прибыль оказалась ниже ожиданий, акции снизились в течение сессии.',
    sentimentScore: -0.5,
  },
  {
    id: 'fin_market_03',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: 'Ставки ЦБ поддержали финсектор',
    body: 'Решение по ключевой ставке воспринято банками позитивно. {company} ({ticker}) выросла на фоне улучшения прогнозов по чистой процентной марже.',
    sentimentScore: 0.35,
  },
  {
    id: 'fin_market_04',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: 'Криптовалютная волатильность давит на {ticker}',
    body: 'Снижение торговых оборотов на цифровых активах отразилось на выручке {company}. Аналитики снизили краткосрочные таргеты по {ticker}.',
    sentimentScore: -0.38,
  },
  {
    id: 'fin_market_05',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: '{company} объявила байбэк',
    body: 'Совет директоров {company} ({ticker}) одобрил программу обратного выкупа акций. Рынок расценил шаг как сигнал уверенности менеджмента в оценке.',
    sentimentScore: 0.42,
  },
  {
    id: 'fin_market_06',
    kind: 'MARKET',
    sector: MarketSector.FINANCE,
    title: 'Финансы: ожидание отчётности',
    body: 'До публикации результатов {company} ({ticker}) участники рынка предпочитали не наращивать позиции. Объёмы торгов остались умеренными.',
    sentimentScore: 0.02,
  },
  {
    id: 'fin_insider_01',
    kind: 'INSIDER',
    sector: MarketSector.FINANCE,
    title: 'Инсайд: крупная сделка у {ticker}',
    body: 'По данным источника, {company} близка к объявлению сделки, которая может заметно изменить структуру доходов.',
    sentimentScore: 0.5,
    expectedMovePercent: 12,
    turnsUntilImpact: 3,
    insiderInfo: 'Источник связан с инвестбанковским подразделением.',
  },
  {
    id: 'fin_insider_02',
    kind: 'INSIDER',
    sector: MarketSector.FINANCE,
    title: 'Инсайд: проверка коснётся {ticker}',
    body: 'Обсуждается внеплановая проверка операций {company}, что может вызвать краткосрочное давление на котировки.',
    sentimentScore: -0.48,
    expectedMovePercent: -11,
    turnsUntilImpact: 2,
    insiderInfo: 'Информация получена от участника рынка межбанковского кредитования.',
  },
  {
    id: 'fin_rumor_01',
    kind: 'RUMOR',
    sector: MarketSector.FINANCE,
    title: 'Слух: слияние вокруг {ticker}',
    body: 'Трейдеры обсуждают возможное объединение {company} с региональным игроком. Официальных заявлений не поступало.',
    sentimentScore: 0.1,
  },
  {
    id: 'fin_rumor_02',
    kind: 'RUMOR',
    sector: MarketSector.FINANCE,
    title: 'Слух: отток крупного клиента из {company}',
    body: 'Анонимный инсайдер утверждает, что {company} ({ticker}) может потерять значимый корпоративный контракт. Компания не комментирует.',
    sentimentScore: -0.2,
  },

  // ── AGRICULTURE ────────────────────────────────────────────────────────────
  {
    id: 'agr_market_01',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: 'Урожай поддержал {ticker}',
    body: 'Отчёт {company} подтвердил рекордные объёмы сбора зерновых. Экспортные контракты обеспечили компании сильный денежный поток.',
    sentimentScore: 0.5,
  },
  {
    id: 'agr_market_02',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: 'Засуха давит на агросектор',
    body: 'Неблагоприятная погода в ключевых регионах ухудшила прогнозы урожайности. {company} ({ticker}) снизилась вместе с отраслевым индексом.',
    sentimentScore: -0.52,
  },
  {
    id: 'agr_market_03',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: '{company}: рост продаж органики',
    body: 'Потребительский спрос на органические продукты поддержал выручку {company} ({ticker}). Маржа оказалась выше консенсуса аналитиков.',
    sentimentScore: 0.36,
  },
  {
    id: 'agr_market_04',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: 'Логистика дорожает для {ticker}',
    body: 'Рост тарифов на перевозку зерна сократил операционную прибыль {company}. Рынок ждёт мер по оптимизации цепочки поставок.',
    sentimentScore: -0.33,
  },
  {
    id: 'agr_market_05',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: 'Вертикальные фермы набирают обороты',
    body: '{company} ({ticker}) открыла новый комплекс в мегаполисе. Проект оценивается как долгосрочный драйвер выручки при высоких стартовых затратах.',
    sentimentScore: 0.28,
  },
  {
    id: 'agr_market_06',
    kind: 'MARKET',
    sector: MarketSector.AGRICULTURE,
    title: 'Агросектор без резких движений',
    body: 'Котировки {company} ({ticker}) торговались в узком коридоре. Участники рынка ждут данных по мировым запасам зерна.',
    sentimentScore: 0.04,
  },
  {
    id: 'agr_insider_01',
    kind: 'INSIDER',
    sector: MarketSector.AGRICULTURE,
    title: 'Инсайд: экспортный контракт для {ticker}',
    body: 'Источник сообщает о подписании крупного экспортного контракта {company}, который пока не раскрыт публично.',
    sentimentScore: 0.52,
    expectedMovePercent: 10,
    turnsUntilImpact: 3,
    insiderInfo: 'Контрагент — международный трейдер сельхозпродукции.',
  },
  {
    id: 'agr_insider_02',
    kind: 'INSIDER',
    sector: MarketSector.AGRICULTURE,
    title: 'Инсайд: вредители угрожают урожаю {ticker}',
    body: 'По внутренним данным, {company} может пересмотреть прогноз урожайности из-за распространения вредителей в ряде регионов.',
    sentimentScore: -0.46,
    expectedMovePercent: -8,
    turnsUntilImpact: 2,
    insiderInfo: 'Информация от агрономической службы контрагента.',
  },
  {
    id: 'agr_rumor_01',
    kind: 'RUMOR',
    sector: MarketSector.AGRICULTURE,
    title: 'Слух: субсидии для {company}',
    body: 'В отрасли обсуждают возможное расширение господдержки, что может затронуть {ticker}. Документы не опубликованы.',
    sentimentScore: 0.14,
  },
  {
    id: 'agr_rumor_02',
    kind: 'RUMOR',
    sector: MarketSector.AGRICULTURE,
    title: 'Слух: проблемы с качеством у {ticker}',
    body: 'На форумах фермеров появились жалобы на партию семян {company}. Пока это единичные сообщения без подтверждения.',
    sentimentScore: -0.16,
  },

  // ── ENERGY ─────────────────────────────────────────────────────────────────
  {
    id: 'energy_market_01',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: 'Нефть дорожает — растёт {ticker}',
    body: 'Рост мировых цен на углеводороды поддержал котировки {company} ({ticker}). Инвесторы пересматривают дивидендные ожидания в сторону повышения.',
    sentimentScore: 0.54,
  },
  {
    id: 'energy_market_02',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: 'Давление на зелёную повестку',
    body: 'Обсуждение новых экологических норм негативно сказалось на секторе традиционной энергетики. {company} ({ticker}) снизилась сильнее индекса.',
    sentimentScore: -0.44,
  },
  {
    id: 'energy_market_03',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: '{company}: рекорд выработки ВИЭ',
    body: 'Солнечные и ветровые активы {company} ({ticker}) вышли на максимальную загрузку за счёт благоприятной погоды в ключевых регионах.',
    sentimentScore: 0.41,
  },
  {
    id: 'energy_market_04',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: 'Аварийный простой бьёт по {ticker}',
    body: '{company} сообщила о внеплановом останове мощностей для технического обслуживания. Сроки возобновления работ пока уточняются.',
    sentimentScore: -0.47,
  },
  {
    id: 'energy_market_05',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: 'Инвестпрограмма {company} одобрена',
    body: 'Совет директоров {company} ({ticker}) утвердил капзатраты на модернизацию сетей. Рынок оценивает решение как поддержку долгосрочной стабильности.',
    sentimentScore: 0.3,
  },
  {
    id: 'energy_market_06',
    kind: 'MARKET',
    sector: MarketSector.ENERGY,
    title: 'Энергетика: боковик',
    body: 'Цены на электроэнергию и сырьё оставались стабильными. {company} ({ticker}) завершила день без выраженного тренда.',
    sentimentScore: 0.03,
  },
  {
    id: 'energy_insider_01',
    kind: 'INSIDER',
    sector: MarketSector.ENERGY,
    title: 'Инсайд: скачок котировок {ticker}',
    body: 'Источник ожидает резкое изменение котировок {company} после публикации данных по добыче, которые пока не в открытом доступе.',
    sentimentScore: 0.56,
    expectedMovePercent: 13,
    turnsUntilImpact: 4,
    insiderInfo: 'Данные получены от оператора отгрузочной инфраструктуры.',
  },
  {
    id: 'energy_insider_02',
    kind: 'INSIDER',
    sector: MarketSector.ENERGY,
    title: 'Инсайд: задержка пуска мощностей {ticker}',
    body: 'Внутренние документы указывают на перенос ввода новых мощностей {company} минимум на два месяца.',
    sentimentScore: -0.5,
    expectedMovePercent: -10,
    turnsUntilImpact: 3,
    insiderInfo: 'Информация от подрядчика строительных работ.',
  },
  {
    id: 'energy_rumor_01',
    kind: 'RUMOR',
    sector: MarketSector.ENERGY,
    title: 'Слух: налог на сверхприбыль энергокомпаний',
    body: 'В СМИ обсуждают возможное налоговое изменение для сектора. {company} ({ticker}) не комментирует, но акции реагировали волатильностью.',
    sentimentScore: -0.12,
  },
  {
    id: 'energy_rumor_02',
    kind: 'RUMOR',
    sector: MarketSector.ENERGY,
    title: 'Слух: {company} продаёт актив',
    body: 'Рынок обсуждает возможную продажу непрофильных активов {company} ({ticker}). Сумма сделки в слухах сильно разнится.',
    sentimentScore: 0.09,
  },
];
